website/auth.py
from flask import ( 
    Blueprint, flash, render_template, request, url_for, redirect
) 
from werkzeug.security import generate_password_hash,check_password_hash
from .models import Users
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db, login_manager


#create a blueprint
bp = Blueprint('auth', __name__)

# Login route
@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        uname = login_form.user_name.data
        password = login_form.password.data
        u1 = Users.query.filter_by(Username=uname).first()
        #if there is no user with that name
        if u1 is None:
            error='Incorrect user name'
        #check the password - notice password hash function
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error)

    return render_template('user.html', form=login_form, heading='Login')

# Register route
@bp.route('/register', methods=['GET','POST'])
def register():
    register = RegisterForm()
    if (register.validate_on_submit() == True):
            #get username, password and email from the form
            uname = register.user_name.data
            fname = register.first_name.data
            lname = register.last_name.data
            pwd = register.password.data
            email=register.email_id.data
            number=register.number.data
            #check if a user exists
            u1 = Users.query.filter_by(Username=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user model object
            new_user = Users(
                Username=uname, FirstName = fname, LastName = lname, 
                password_hash=pwd_hash, Email=email, ContactNumber=number)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')

# Logout route
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request
from .models import Events, Bookings
from flask_login import login_required, current_user
bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    #If the user search for events, return results, else, return everything else.
    search = request.args.get("search")
    if search is not None:
        eventName = "%" + request.args["search"] + "%"
        events = Events.query.filter(Events.EventName.like(eventName)).all()

        cities = ["All"]
        for event in events:
            if event.City not in cities:
                cities.append(event.City)

        return render_template("index.html", events = events, cities = cities)
    
    events = Events.query.all()
    cities = ["All"]
    for event in events:
        if event.City not in cities:
            cities.append(event.City)

    return render_template("index.html", events = events, cities = cities) # currently incorrect

@bp.route('/UserBookingHistory')
@login_required
def userBookingHistory():
    bookings = Bookings.query.filter_by(User_id = current_user.UserId)
    return render_template("userBookingHistory.html", bookings = bookings)

@bp.route('/UserSettings')
def userSettings():
    return render_template("userSettings.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        {% endblock %}
    </head>

    <body>
        <!-- Navbars -->
        <nav class="navbar navbar-expand-xl navbar-dark text-light p-2 navBgColor justify-content-start p-3">
            <!-- Header and nav collapse button-->
            <div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <a class="navbar-brand m-2" href="{{ url_for('main.index') }}">Sport Events</a>
            </div>
        
            <div class="collapse navbar-collapse justify-content-between navItems" id="navCollapse">
                <!-- Search form-->
                <form class="form-inline navInput" style="margin-left: -9.5px;" method="GET" action="{{ url_for('main.index') }}">
                    <div class="d-flex">
                        <input class="form-control m-2" type="text" placeholder="Search" name="search">
                        <button class="btn btn-outline-success m-2" type="submit">Search</button>
                    </div>
                </form>
        
                <!-- Other links-->
                {% block navlinks %}
                    {% if current_user.is_authenticated %}
                        <ul class="navbar-nav mr-auto" style="margin-left: -32px;">
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('event.update') }}">My Events</a>
                            </ul>
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('event.create') }}">Create an event</a>
                            </ul>
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.userBookingHistory') }}">Booking history</a>
                            </ul>
                            <ul class="nav-item">
                                <a class="nav-link disabled text-muted" href="#">Welcome, {{current_user.FirstName}}</a>
                            </ul>
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                            </ul>
                        </ul>
                    {% else %}
                        <ul class="navbar-nav mr-auto" style="margin-left: -32px;">
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">Create an account</a>
                            </ul>
                            <ul class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
                            </ul>
                        </ul>
                    {% endif %}
                {% endblock %}
            </div>
        </nav>


        <main>
            {% block content %}
            {% endblock %}
        </main>

        <div class="p-4"></div>

        <footer class="text-center text-lg-start bg-light text-muted">
            <div class="p-1"></div>
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Sport Events</h6>
                        <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt iure consectetur necessitatibus ipsam nemo accusamus dolore. Ducimus est ipsam exercitationem perferendis, minima, quidem provident totam blanditiis a porro illo eos!
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p>Townsville, QLD 4818, AU</p>
                        <p>n11247321@qut.edu.au</p>
                        <p>+ 61 234 567 88</p>
                        <p>+ 61 234 567 89</p>
                    </div>
                </div>
            </div>

            <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                © 2022 Copyright:
                <a class="text-reset fw-bold" href="https://qut.edu.au">QUT.edu.au</a>
            </div>
        </footer>


        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script>changeMargin();</script>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

website/templates/event.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/event.css">
    <script src="../static/js/EventRating.js"></script>
    <script src="../static/js/TicketPrice.js"></script>
    <script src="../static/js/UpdateReview.js"></script>
{% endblock %}

{% import "bootstrap/form.html" as wtf %}

{% block content %}
    <div class="p-4" id="navbarSpacer"></div>

    <div id="eventImg">
        <img src="{{event.Image}}" id="eventImg2">
    </div>

    <div class="container-fluid" id="mainBox">
        <div id="imgSpacer"></div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in get_flashed_messages() %}
               <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
                 {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

        <h1>{{event.EventName}} - {{event.Status}}</h1>
        <div class="p-2"></div>
        <div class="container-fluid eventInfo">
            <p class="eventDateTime">{{event.StartDate}} - {{event.EndDate}}</p>
            <div class="p-2"></div>
            <p>{{event.CatergoryName}}</p>
            <div class="p-2"></div>
            <p>{{event.description}}</p>
            <div class="p-2"></div>
            <p>Location: {{event.Location}}</p>
            <div class="p-2"></div>
            <p class="eventTickets">{{remainder}} tickets available</p>
            <div class="p-2"></div>

            {% if current_user.is_authenticated %}
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#ticketModal">
                    Book tickets
                </button>
                
                <div class="modal fade" id="ticketModal" tabindex="-1" role="dialog" aria-labelledby="ticketModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="ticketModalLabel">Purchase tickets</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>

                            </div>
                            <div class="modal-body">
                                <form method="post" action="{{ url_for('event.book', id=event.EventId)}}">
                                    {{ form.csrf_token }}
                                    <h4>Number of tickets:</h4>
                                    <div style="width: 80px;">
                                        <input type="hidden" id="hiddenPrice" value="{{ event.TicketPrice }}">
                                        {{ dform.ticket_num(class_="form-control", id_="ticketNumber", placeholder="Number of tickets", value=1, onchange_="updatePrice(ticketPrice)") }}
                                    </div>
                                    <div class="p-2"></div>
                                    <h5 id="ticketPrice">Total price: $30</h5>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                        {{ dform.submit(class_="btn btn-success btn-md") }}
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="p-4"></div>

        <!-- Create and post reviews -->
        {% if current_user.is_authenticated %}
            <div class="p-3 review">
                <h2>Post a review:</h2>
                <div class="p-2"></div>
                <form method="post" action>
                    {{ form.csrf_token }}
                    
                    <div class="form-group row">
                        <div class="col-lg-12">
                            {{ form.title(class_="form-control", placeholder="Review Title") }}
                        </div>
                    </div>

                    <div class="p-2"></div>
                    <div class="form-group">
                        {% set i = 1 %}
                        {% for subfield in form.rating %}
                            {{ subfield(class_="ratingRadio", onchange_="EventRating()") }}
                            <label class="ratingLabel" for="rating-{{ loop.index - 1 }}">
                                <span class="fa fa-star rating"></span>
                            </label>
                        {% endfor %}
                    </div>
                    
                    <div class="p-2"></div>
                    <div class="form-group row">
                        <div class="col-lg-12">
                            {{ form.comment(class_="form-control", rows=5) }}
                        </div>
                    </div>

                    <div class="p-1 lineBreaks"></div>
                    {{ form.submit(class_="btn btn-success") }}

                </form>
            </div>
        {% endif %}

        <div class="p-1 lineBreaks"></div>
        <div class="p-1 lineBreaks"></div>

    <!-- Display reviews for the event -->  
      
        <div class="row border-bottom">  
            {% for review in event.reviews %}

            <div class="col-md-12">  
                <div class="p-3 review">
                    <h2>{{ review.Title }}</h2>
                    <p>{{ review.user.Username }} - {{ review.CreatedAt.strftime('%Y/%m/%d') }}</p>
                    <div id="ratingDiv">
                        {% for i in range(review.Rating) %}
                            <span class="fa fa-star rating checked"></span>
                        {% endfor %}
                        {% for i in range(5 - review.Rating) %}
                            <span class="fa fa-star rating"></span>
                        {% endfor %}
                    </div>
                    <div class="p-2"></div>
                    <p>{{ review.Content }}</p>
            </div>
            <div class="p-2"></div>
            {% endfor %} 
        </div>
        

        

    </div>

{% endblock %}
{% block scripts %}
<script>
    var ticketPrice = parseInt(document.getElementById("hiddenPrice").value);
    updatePrice(ticketPrice);
</script>
{% endblock %}

website/templates/eventCreation.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link type="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/eventCreation.css">
{% endblock %}

{% import "bootstrap/form.html" as wtf %}
{% block content %}
    <div class="container-fluid eventForm">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in get_flashed_messages() %}
               <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
                 {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <div class="p-4"></div>
        <h1>Event Details:</h1>
        <hr>
        <div class="p-2"></div>
        <form method="post" enctype="multipart/form-data" action>
            {{ form.csrf_token }}
            
            <div class="form-group row">
                <div class="col-lg-9">
                    <h4>Event name:</h4>
                    {{ form.event_name(class_="form-control", placeholder="Event Name") }}
                </div>
                
                <div class="col-lg-3">
                    <h4>Status:</h4>
                    {{ form.Status_id(class_="form-control") }}
                </div>
            </div>
            

            <div class="p-1"></div>
            <div class="form-group row">
                <div class="col-xl-6 col-lg-12">
                    <h4>Location:</h4>
                    {{ form.location(class_="form-control", placeholder="Location") }}
                </div>

                <div class="p-1 lineBreaks"></div>
                <div class="col-xl-3 col-lg-6 col-sm-12">
                    <h4>City:</h4>
                    {{ form.city(class_="form-control", placeholder="City") }}
                </div>

                <div class="p-1 lineBreaks"></div>
                <div class="col-xl-3 col-lg-6 col-sm-12">
                    <h4>Sport:</h4>
                    {{ form.Catergory_id(class_="form-control") }}
                </div>
                
            </div>

            <div class="p-1"></div>
            <div class="form-group row">
                <div class="col-lg-6 col-sm-12">
                    <div class="row">
                        <div class="col-sm-6 col-xs-12">
                            <h4>Start:</h4>
                            {{ form.start_time(class_="form-control") }}
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <h4>End:</h4>
                            {{ form.end_time(class_="form-control") }}
                        </div>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="p-1 lineBreaks"></div>
                    <h4>Number of tickets:</h4>
                    {{ form.max_tickets(class_="form-control", placeholder="Number of tickets", value=1) }}
                </div>
                <div class="col-lg-3">
                    <div class="p-1 lineBreaks"></div>
                    <h4>Ticket price:</h4>
                    {{ form.ticket_price(class_="form-control", placeholder="Ticket Price") }}
                </div>
            </div>

            <div class="p-1"></div>

            <div class="p-4"></div>
            <div class="col-12">
                <h4>Description:</h4>
                {{ form.description(class_="form-control", rows=5) }}
                <br>
                <h4>Choose an image:</h4>
                {{ form.image(class_="form-control-file") }}
            </div>
            <br>
            {{ form.submit(class_="btn btn-primary btn-md") }}
        </form>
    </div>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/index.css">
    <script src="../static/js/IndexResponsive.js"></script>
    <script src="../static/js/eventCategories.js"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid m-auto" id="mainBox">
        <div class="UpcomingEventHeader" id="UpcomingEventHeader">
            <form class="form-inline" style="display: inline-block;">
                <h1>Upcoming events in:</h1>
                <select class="form-select form-select-lg" id="citySelect" onchange="SportCategories()">
                    {% for city in cities %}
                        <option>{{ city }}</option>
                    {% endfor %}
                </select>
            </form>
        </div>

        <div id="SportCategories">
            <form>
                <div class="d-flex flex-row justify-content-center flex-wrap">
                    <div class="noselect">
                        <input type="checkbox" id="cat1" class="catCheckbox" name="sportCat" value="1" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat1">
                            <img class="pictoImg" src="../static/img/pictoImg/basketball.png">
                            Basketball
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat2" class="catCheckbox" name="sportCat" value="2" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat2">
                            <img class="pictoImg" src="../static/img/pictoImg/cricket.png">
                            Cricket
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat3" class="catCheckbox" name="sportCat" value="3" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat3">
                            <img class="pictoImg" src="../static/img/pictoImg/gymnastics.png">
                            Gymnastics
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat4" class="catCheckbox" name="sportCat" value="4" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat4">
                            <img class="pictoImg" src="../static/img/pictoImg/netball.png">
                            Netball
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat5" class="catCheckbox" name="sportCat" value="5" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat5">
                            <img class="pictoImg" src="../static/img/pictoImg/nfl.png">
                            Football
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat6" class="catCheckbox" name="sportCat" value="6" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat6">
                            <img class="pictoImg" src="../static/img/pictoImg/nrl.png">
                            Rugby
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat7" class="catCheckbox" name="sportCat" value="7" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat7">
                            <img class="pictoImg" src="../static/img/pictoImg/swimming.png">
                            Swimming
                        </label>
                    </div>
                    <div class="noselect">
                        <input type="checkbox" id="cat8" class="catCheckbox" name="sportCat" value="8" onchange="SportCategories()">
                        <label class="p-3 m-1 sportPicto" for="cat8">
                            <img class="pictoImg" src="../static/img/pictoImg/tennis.png">
                            Tennis
                        </label>
                    </div>
                </div>

            </form>
            <div class="d-flex flex-row justify-content-center flex-wrap">
                
            </div>
        </div>
        <div class="p-3"></div>
        <div class="d-flex flex-wrap justify-content-around">

            {% for event in events %}
            {% if (event.Status_id != 2) %}
                <section id="firstEventItem" class="category{{ event.Catergory_id }} eventItems" data-city="{{ event.City }}">
                    <a href="{{url_for('event.show', id=event.EventId)}}" class="EventLink">
                        <div class="eventImgContainer">
                            <img class="eventImg" src="{{event.Image}}" alt="{{event.EventName}}">
                        </div>

                        <div class="eventItem p-3">
                            <h2>{{event.EventName}} - {{event.Status}}</h2>
                            <p class="eventDateTime">Starting: {{event.StartDate}}</p>
                            <p class="eventDateTime">Ending: {{event.EndDate}}</p>
                            <p style="font-weight: bold;">Sport: {{event.CatergoryName}}</p>
                            <div class="eventDescription">
                                <p>{{event.description}}</p>
                            </div>
                        </div>
                        <p class="eventTickets">Tickets: {{event.MaxTickets}}</p>
                    </a>
                </section>
                {% endif %}
            {% endfor %} 

        </div>
    </div>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/form.html" as wtf %}

{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/user.css">
{% endblock %}

{% block content %}



    <div class="container-fluid">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

    </div>



    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="container" id="mainBox">
        <div class="p-4"></div>
        <div class="p-2"></div>
        <h1>{{ heading }}</h1>
        <hr>
        <div class="p-2"></div>
        <!-- When you have login form, then do show the user a link to register -->
        <form method="post" enctype="multipart/form-data" action>
            {{ form.csrf_token }}

            {% if heading|lower =='login' %}
                    <label for="user_name">Username: </label>
                    {{ form.user_name(class_="form-control", placeholder="Username") }}
                    <div class="p-1"></div>
                    <label for="password">Password: </label>
                    {{ form.password(class_="form-control", placeholder="Password") }}
                    <br>

                    {{ form.submit(class_="btn btn-primary btn-md") }}
                    <div class="p-1"></div>
                    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
                    <div class="p-4"></div>
                    <div class="p-3"></div>
            {% else %}
                <label for="user_name">Username: </label>
                {{ form.user_name(class_="form-control", placeholder="Username") }}
                <div class="p-1"></div>

                <div class="row">
                    <div class="col-sm-6 col-xs-12">
                        <label for="first_name">First name: </label>
                        {{ form.first_name(class_="form-control", placeholder="First name") }}
                        <div class="p-1"></div>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <label for="last_name">Last name: </label>
                        {{ form.last_name(class_="form-control", placeholder="Last name") }}
                        <div class="p-1"></div>
                    </div>
                    
                </div>
                

                

                <label for="email_id">Email: </label>
                {{ form.email_id(class_="form-control", placeholder="Email") }}
                <div class="p-1"></div>

                <label for="number">Phone number: </label>
                {{ form.number(class_="form-control", placeholder="Phone number") }}
                <div class="p-1"></div>

                <label for="password">Password: </label>
                {{ form.password(class_="form-control", placeholder="Password") }}
                <div class="p-1"></div>

                <label for="confirm">Confirm password: </label>
                {{ form.confirm(class_="form-control", placeholder="Confirm password") }}

                <br>

                {{ form.submit(class_="btn btn-primary btn-md") }}
                <div class="p-1"></div>
                <p>Already have an account? <a href="{{ url_for('auth.login') }}">Click here to log in</a>.</p>
            {% endif %}
        </form>
    </div>

    

{% endblock %}